# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 5432 %>


  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
development:
  <<: *default
  adapter: postgresql
  database: render_dev
  username: postgres
  password: password
  host: localhost
 
test:
  <<: *default
  adapter: postgresql
  database: render_test
  username: postgres
  password: password
  host: localhost

# production:
#   <<: *default
#   adapter: postgresql
#   database: <%= ENV['TEMPLATEAPP_DATABASE'] %>
#   username: <%= ENV['TEMPLATEAPP_DATABASE_USER'] %>
#   password: <%= ENV['TEMPLATEAPP_DATABASE_PASSWORD'] %>
#   host: <%= ENV['TEMPLATE_DATABASE_HOSTNAME'] %>
#   port: 5432

